services:
  mariadb:
    container_name: firefox_mariadb
    image: linuxserver/mariadb:10.6.13
    volumes:
      - ./dbdata:/config
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: syncstorage
      MYSQL_USER: sync
      MYSQL_PASSWORD: YOUR_RANDOM_MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: YOUR_RANDOM_MYSQL_ROOT_PASSWORD

  syncserver:
    container_name: firefox_syncserver
    build: ./FiTaDoServer
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    environment:
      LOGLEVEL: info
      SYNC_URL: http://TAILSCALE_IP:8000
      SYNC_CAPACITY: 10 # Max number of users that will be accepted
      SYNC_MASTER_SECRET: YOUR_RANDOM_SYNC_MASTER_SECRET
      METRICS_HASH_SECRET: YOUR_RANDOM_METRICS_HASH_SECRET
      SYNC_SYNCSTORAGE_DATABASE_URL: mysql://sync:YOUR_RANDOM_MYSQL_PASSWORD@mariadb:3306/syncstorage_rs
      SYNC_TOKENSERVER_DATABASE_URL: mysql://sync:YOUR_RANDOM_MYSQL_PASSWORD@mariadb:3306/tokenserver_rs
